name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      
      - name: Install dependencies
        run: npm ci

      - name: Build Extension
        run: node index.js

      - name: Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "discrilkx379@gmail.com"
          git config --global user.name "Death-Knight-552"
          git tag -a ${{ github.event.inputs.version }} -m "Version ${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: |
            build/*
      



